//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.DataBase.DataAccess
{
    using System;
    
    public partial class ControleFila
    {
        public string FILA { get; set; }
        public int TOTAL_DISPONIVEIS { get; set; }
        public int INSTANCIAS { get; set; }
        public int EM_USO { get; set; }
        public int MAQUINAS { get; set; }
    }
}
