//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.DataBase.DataAccess
{
    using System;
    
    public partial class DetalhamentoResult
    {
        public int id { get; set; }
        public string CorLinha { get; set; }
        public string Modalidade { get; set; }
        public string Tabulacao { get; set; }
        public int Total { get; set; }
        public decimal percentual { get; set; }
    }
}
