//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.DataBase.DataAccess
{
    using System;
    
    public partial class DetalhamentoErroSiebelResult
    {
        public string CPF { get; set; }
        public string Nome { get; set; }
        public string nacimento { get; set; }
        public string NomeMae { get; set; }
        public string Sexo { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Plano { get; set; }
        public string tpPagamento { get; set; }
        public string modeloPagamento { get; set; }
        public string CEP { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string criacao { get; set; }
        public string modificacao { get; set; }
        public string numeroPedido { get; set; }
        public string CodPDV { get; set; }
        public string numeroChip { get; set; }
        public string modalidade { get; set; }
        public string diaPgt { get; set; }
        public string operadora { get; set; }
        public string operadoraAtual { get; set; }
        public string tp { get; set; }
        public string tabulacaoWooza { get; set; }
        public string descricao { get; set; }
        public string janelaPortabilidade { get; set; }
        public int id { get; set; }
        public string CorLinha { get; set; }
    }
}
