//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.DataBase.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Indigosoft_Workflow_WoozaEntities : DbContext
    {
        public Indigosoft_Workflow_WoozaEntities()
            : base("name=Indigosoft_Workflow_WoozaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<UsuarioResult> STP_LOGIN_DASHBOARD(string login, string senha)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var senhaParameter = senha != null ?
                new ObjectParameter("senha", senha) :
                new ObjectParameter("senha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioResult>("STP_LOGIN_DASHBOARD", loginParameter, senhaParameter);
        }
    
        public virtual ObjectResult<TotalTipoResult> STP_TOTAL_TIPO_DASHBOARD(Nullable<System.DateTime> dtInicio, Nullable<System.DateTime> dtFim)
        {
            var dtInicioParameter = dtInicio.HasValue ?
                new ObjectParameter("DtInicio", dtInicio) :
                new ObjectParameter("DtInicio", typeof(System.DateTime));
    
            var dtFimParameter = dtFim.HasValue ?
                new ObjectParameter("DtFim", dtFim) :
                new ObjectParameter("DtFim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalTipoResult>("STP_TOTAL_TIPO_DASHBOARD", dtInicioParameter, dtFimParameter);
        }
    
        public virtual ObjectResult<DetalhamentoResult> STP_DETALHAMENTO_DASHBOARD(Nullable<System.DateTime> dtInicio, Nullable<System.DateTime> dtFim, string modalidade, Nullable<int> tipo)
        {
            var dtInicioParameter = dtInicio.HasValue ?
                new ObjectParameter("DtInicio", dtInicio) :
                new ObjectParameter("DtInicio", typeof(System.DateTime));
    
            var dtFimParameter = dtFim.HasValue ?
                new ObjectParameter("DtFim", dtFim) :
                new ObjectParameter("DtFim", typeof(System.DateTime));
    
            var modalidadeParameter = modalidade != null ?
                new ObjectParameter("modalidade", modalidade) :
                new ObjectParameter("modalidade", typeof(string));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalhamentoResult>("STP_DETALHAMENTO_DASHBOARD", dtInicioParameter, dtFimParameter, modalidadeParameter, tipoParameter);
        }
    
        public virtual ObjectResult<DetalhamentoErroSiebelResult> STP_DETALHAMENTO_ERROS_SIEBEL(Nullable<System.DateTime> dtInicio, Nullable<System.DateTime> dtFim, string modalidade, string tabulacao)
        {
            var dtInicioParameter = dtInicio.HasValue ?
                new ObjectParameter("DtInicio", dtInicio) :
                new ObjectParameter("DtInicio", typeof(System.DateTime));
    
            var dtFimParameter = dtFim.HasValue ?
                new ObjectParameter("DtFim", dtFim) :
                new ObjectParameter("DtFim", typeof(System.DateTime));
    
            var modalidadeParameter = modalidade != null ?
                new ObjectParameter("Modalidade", modalidade) :
                new ObjectParameter("Modalidade", typeof(string));
    
            var tabulacaoParameter = tabulacao != null ?
                new ObjectParameter("Tabulacao", tabulacao) :
                new ObjectParameter("Tabulacao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalhamentoErroSiebelResult>("STP_DETALHAMENTO_ERROS_SIEBEL", dtInicioParameter, dtFimParameter, modalidadeParameter, tabulacaoParameter);
        }
    
        public virtual ObjectResult<ControleFila> STP_CONTROLE_FILA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ControleFila>("STP_CONTROLE_FILA");
        }
    }
}
