//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.DataBase.DataAccess
{
    using System;
    
    public partial class TotalTipoResult
    {
        public string Modalidade { get; set; }
        public int Sucesso { get; set; }
        public int Erro { get; set; }
        public decimal Resultado { get; set; }
        public int Aptas { get; set; }
        public decimal PercentualAptas { get; set; }
        public string CorLinha { get; set; }
        public int Total { get; set; }
    }
}
